
- name: "Setting cluster config variables"
  set_fact:
    other_node_pool_initial_node_count: 4
    flink_node_pool_initial_node_count: 6
    initial_cluster_version: "1.23"

- name: "Create a GKE cluster"
  google.cloud.gcp_container_cluster:
    name: ansible-cluster
    initial_cluster_version: "{{ initial_cluster_version }}"
    initial_node_count: "{{ other_node_pool_initial_node_count + flink_node_pool_initial_node_count }}"
    location: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    release_channel:
      channel: "UNSPECIFIED"
    ip_allocation_policy:
      use_ip_aliases: "yes"
    default_max_pods_constraint:
      max_pods_per_node: "110"
    addons_config:
      horizontal_pod_autoscaling:
        disabled: "no"
      http_load_balancing:
        disabled: "no"
    network: "projects/{{ gcp_project }}/global/networks/{{ network }}"
    subnetwork: "projects/{{ gcp_project }}/regions/{{ gcp_region }}/subnetworks/{{ subnet }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ cluster_state }}"
  register: cluster

- name: "Create other node pool for the GKE cluster"
  google.cloud.gcp_container_node_pool:
    name: other-pool
    initial_node_count: "{{ other_node_pool_initial_node_count }}"
    cluster: "{{ cluster }}"
    location: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    config:
      machine_type: "{{ gcp_machine_type }}"
      image_type: "cos_containerd"
      labels: { "component": "other" }
      disk_size_gb: 100
      oauth_scopes:
        - "https://www.googleapis.com/auth/devstorage.read_only"
        - "https://www.googleapis.com/auth/logging.write"
        - "https://www.googleapis.com/auth/monitoring"
        - "https://www.googleapis.com/auth/servicecontrol"
        - "https://www.googleapis.com/auth/service.management.readonly"
        - "https://www.googleapis.com/auth/trace.append"
    management:
      auto_repair: "yes"
      auto_upgrade: "yes"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ cluster_state }}"

- name: "Create flink node pool for the GKE cluster"
  google.cloud.gcp_container_node_pool:
    name: flink-pool
    initial_node_count: "{{ flink_node_pool_initial_node_count }}"
    cluster: "{{ cluster }}"
    location: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    config:
      machine_type: "{{ gcp_machine_type }}"
      image_type: "cos_containerd"
      labels: { "component": "flink" }
      disk_size_gb: 100
      oauth_scopes:
        - "https://www.googleapis.com/auth/devstorage.read_only"
        - "https://www.googleapis.com/auth/logging.write"
        - "https://www.googleapis.com/auth/monitoring"
        - "https://www.googleapis.com/auth/servicecontrol"
        - "https://www.googleapis.com/auth/service.management.readonly"
        - "https://www.googleapis.com/auth/trace.append"
    management:
      auto_repair: "yes"
      auto_upgrade: "yes"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ cluster_state }}"

- name: "Connect to cluster (update kubeconfig)"
  shell: "gcloud container clusters get-credentials {{ cluster.name }} --zone {{ gcp_zone }} --project {{ gcp_project }}"
  when: cluster_state == "present"